---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ricochet
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: website
        image: amazonaws.com/ricochet
        resources:
            limits:
              memory: 2048Mi
            requests:
              memory: 2048Mi
              cpu: 100m
        livenessProbe:
          httpGet:
            path: /index.html
        imagePullPolicy: Always
        env:
        - name: IMAGE_TAG
          value: kustomized_ricochet
        ports:
        - containerPort: 3000
          name: frontend
