name: test

on:
  push:
    branches:
      - main
      - v2
  pull_request:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        yarn install
    - run: yarn tsc
    - run: yarn build
    - run: npm test
